ASoC: fsi: fixup compile error for simple-card
This patches fixes
c7a507eea1db1430476289f525f9c853d5d485e8
(ASoC: fsi: fixup SND_SOC_DAIFMT_CBx_CFx flags)
commit's compie error

arch/arm/mach-shmobile/board-mackerel.c:512:2: \
  error: unknown field 'fmt' specified in initializer

Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Acked-by: Simon Horman <horms+renesas@verge.net.au>
Signed-off-by: Mark Brown <broonie@linaro.org>
Signed-off-by: Ryo Kataoka <ryo.kataoka.wt@renesas.com>

Conflicts:
	arch/arm/mach-shmobile/board-mackerel.c

(cherry picked from commit 354da5344ae0c595ac170340fbd5e2f7317a1635)
Signed-off-by: Ryo Kataoka <ryo.kataoka.wt@renesas.com>